version: "2"

# Have to make it the hard way (not via aggregator linter) because I need a fine control of staticcheck
# ... but it's also sort of convenient to use the same makefile as locally
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install linters
      run: make install_linters

    - name: Check
      run: make check
