// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/limiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRequest) Reset() {
	*x = RequestRequest{}
	mi := &file_proto_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRequest) ProtoMessage() {}

func (x *RequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRequest.ProtoReflect.Descriptor instead.
func (*RequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       int32                  `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_proto_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *RequestResponse) GetGranted() int32 {
	if x != nil {
		return x.Granted
	}
	return 0
}

var File_proto_limiter_proto protoreflect.FileDescriptor

const file_proto_limiter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/limiter.proto\x12\alimiter\":\n" +
	"\x0eRequestRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"+\n" +
	"\x0fRequestResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\x05R\agranted2G\n" +
	"\aLimiter\x12<\n" +
	"\aRequest\x12\x17.limiter.RequestRequest\x1a\x18.limiter.RequestResponseB'Z%github.com/mgumerov/limiter/api/protob\x06proto3"

var (
	file_proto_limiter_proto_rawDescOnce sync.Once
	file_proto_limiter_proto_rawDescData []byte
)

func file_proto_limiter_proto_rawDescGZIP() []byte {
	file_proto_limiter_proto_rawDescOnce.Do(func() {
		file_proto_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)))
	})
	return file_proto_limiter_proto_rawDescData
}

var file_proto_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_limiter_proto_goTypes = []any{
	(*RequestRequest)(nil),  // 0: limiter.RequestRequest
	(*RequestResponse)(nil), // 1: limiter.RequestResponse
}
var file_proto_limiter_proto_depIdxs = []int32{
	0, // 0: limiter.Limiter.Request:input_type -> limiter.RequestRequest
	1, // 1: limiter.Limiter.Request:output_type -> limiter.RequestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_limiter_proto_init() }
func file_proto_limiter_proto_init() {
	if File_proto_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_limiter_proto_goTypes,
		DependencyIndexes: file_proto_limiter_proto_depIdxs,
		MessageInfos:      file_proto_limiter_proto_msgTypes,
	}.Build()
	File_proto_limiter_proto = out.File
	file_proto_limiter_proto_goTypes = nil
	file_proto_limiter_proto_depIdxs = nil
}
